---
title: "PUG Blog Project Data Wrangling"
author: "Majd Rouhana, Elizabeth Tran, Charlie Estes"
date: "11/06/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
```

## Wrangling

```{r}
# reading in and wrangling csv for resp. disease rates
clrdms <- read_csv("Chronic Lower Respiratory Disease Mortality by State.csv") %>%
  filter(YEAR == 2018) %>%
  mutate(`State Abbreviation` = STATE, Rate = RATE, Deaths = DEATHS) %>%
  select(`State Abbreviation`, Rate, Deaths)

# reading in and wrangling csv for educational attainment
eduData <- read_csv("csvData.csv") %>%
  arrange(State) %>%
  filter(State != "Puerto Rico", State != "Washington DC") %>%
  mutate(`State Abbreviation` = clrdms$`State Abbreviation`)

# joining the previous two datasets
data <- clrdms %>%
  inner_join(eduData)

# reading in and wrangling csv for state carbon emissions
carbonData <- read_csv("carbonData.csv") %>%
  na.omit() %>%
  filter(State != "Total of states (unadjusted)?", State != "United States", State != "District of Columbia") %>%
  mutate(`C02 Emission` = `2017`) %>%
  select(State, `C02 Emission`)

# reading in and wrangling csv for per capita state carbon emissions
perCapita <- read_csv("perCapita.csv") %>%
  na.omit() %>%
  filter(State != "Average all states") %>%
  mutate(`Per Capita C02 Emission` = `2017`) %>%
  select(State, `Per Capita C02 Emission`)

# joining the previous two datasets with the `data` dataset
data2 <- carbonData %>%
  inner_join(perCapita)

# reading in and wrangling csv for median income by state
medianIncome <- read_csv("medianIncome.csv") %>%
  filter(State != "D.C.")

# reading in and wrangling csv for party affiliation by state
partyAffiliation <- read_csv("partyAffiliation.csv") %>%
  mutate(party = ifelse(Democrat > Republican, "Democrat", "Republican"))


# joining all of the datasets for our final dataset
blogData <- data %>%
  inner_join(data2) %>%
  inner_join(medianIncome) %>%
  inner_join(partyAffiliation)

#creating data to be mapped
library(fivethirtyeight)
library(maps)
library(ggplot2)
library(viridis)

usa_states <- map_data(map = "state"
, region = ".")

usa_states

data_for_mapping <- blogData %>% 
  mutate(region = tolower(State)) %>%
  right_join(usa_states, by = "region") %>%
  rename(perCapitaC02 = `Per Capita C02 Emission`)




ggplot(data_for_mapping, aes(x = long, y = lat, group = group , fill = perCapitaC02)) +
geom_polygon(color = "white") +
theme_void() +
coord_fixed(ratio = 1.3) +
labs(title = ""
, fill = "") + scale_color_viridis(option = "plasma")
```

